version: '2'

services:
  lpd_server:
    image: eeacms/lpd
    environment:
    - SCK_PRIVATE_EXPORT_TEMPLATE=E:/lpd_folder/templates/reporting/export.xlsx
    - SCK_PUBLIC_EXPORT_TEMPLATE=E:/lpd_folder/templates/reporting/export.xls
    - SCK_EXPORT_FOLDER=E:/lpd_folder/exports
    - SCK_REPORT_PROVIDER=http://lpddevelop.eionet.europa.eu/lpd_archive_provider/ReportProvider
    - SCK_REPORT_SUPPORT_MAIL=support@lpd.com
    - SCK_SUPER_ADMIN=heerearn
    - SCK_BING_KEY=changeme
    - SCK_SHAPEFILE_IMPORT_SERVICE_URL=https://lpddevelop.discomap.eea.europa.eu/arcgis/rest/services/LPD/shapefileImportModel/GPServer/shapefileImportModel
    - SCK_SHAPEFILE_FOLDER=E:/lpd_folder/tmp
    - SCK_SHAPEFILE_TPL_FOLDER=E:/lpd_folder/templates/shapefile
    - SCK_DOCUMENTATIONFILE_FOLDER=E:/lpd_folder/documentation
    - SCK_USER_GUIDE_FOLDER=E:/lpd_folder/templates/userguide
    - SCK_ARCHIVE_PROVIDER=http://lpddevelop.eionet.europa.eu/lpd_archive_provider/ArchiveProvider
    - SCK_DOCUMENTATION_PROVIDER=http://lpddevelop.eionet.europa.eu/lpd_archive_provider/DocumentationProvider
    - SCK_TEMPLATE_PROVIDER=http://lpddevelop.eionet.europa.eu/lpd_archive_provider/TemplateProvider
    - SCK_USER_GUIDE_PROVIDER=http://lpddevelop.eionet.europa.eu/lpd_archive_provider/UserGuideProvider
    - SCK_BENEFICIARY_FEATURE_LAYER_URL=https://lpddevelop.discomap.eea.europa.eu/arcgis/rest/services/LPD/beneficiaryLayer_production/MapServer/0
    - SCK_BENEFICIARY_PUBLIC_LAYER=https://bio.discomap.eea.europa.eu/arcgis/rest/services/ProtectedSites/CDDA_Dyna_LAEA/MapServer
    - SCK_ARCGIS_PROXY=http://lpddevelop.eionet.europa.eu/lpd_web/ArcGISProxy
    - SCK_SPATIAL_REFERENCE=3857
    - SCK_BACKGROUND_LAYER=http://server.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/0
    - mail.smtp.host=changeme
    - mail.smtp.user=changeme
    - SCK_MAIL_SMTP_PASSWORD=changeme
    - SCK_MAIL_STMP_FROM_FOR_BENEF=changeme
    - SCK_MAIL_OUTCOPY=changeme
    - SCK_MAIL_QC=changeme
    - SCK_TABLE_PREFIX=lpd_production.DBO
    - SCK_LPD_WEB_APPLICATION=http://lpddevelop.eionet.europa.eu/lpd_web
    - SCK_AUTH=beneficiary/desk_officer:cn=extranet-landpurchase-deskofficer,cn=extranet-landpurchase,cn=extranet,ou=Roles,o=EIONET,l=Europe/quality_control:cn=extranet-landpurchase-qualitycontrol,cn=extranet-landpurchase,cn=extranet,ou=Roles,o=EIONET,l=Europe/admin:cn=extranet-landpurchase-admin,cn=extranet-landpurchase,cn=extranet,ou=Roles,o=EIONET,l=Europe
    - SCK_LDAP_URL=changeme
    - SCK_LDAP_UID=changeme
    - SCK_LDAP_BASE_CONTEXT=changeme
    - SCK_BENEFICIARY_ACCESS_ACTIVATION_TOKEN_VALIDITY=10
    - SCK_BENEFICIARY_ACCESS_VALIDITY=180
    - LPD_PRINT_SERVICE=https://lpddevelop.discomap.eea.europa.eu/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task
    - LPD_EXTRACT_SPATIAL_DATA_SERVICE=https://lpddevelop.discomap.eea.europa.eu/arcgis/rest/services/LPD/ExtractSpatialDataTool/GPServer/Extract%20data%20on%20expression
    - LPD_SEARCH_LAYER=https://lpddevelop.discomap.eea.europa.eu/arcgis/rest/services/LPD/beneficiaryLayer_production/FeatureServer/0
     #use \ if connection url contain /
    - DBCONNECTION_URL=jdbc:sqlserver:\/\/LIONFISH;databaseName=lpd_production;integratedSecurity=true
      #driver=sqlserver
    - DBCONNECTION_USERNAME=dbuser
    - DBCONNECTION_PASSWORD=dbpass
    - JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
    - JBOSS_HOME=/opt/jboss/jboss-as-7.1.1.Final
    
    container_name: lpd-server
    volumes:
    - jboss_deployments:/opt/jboss/jboss-as-7.1.1.Final/standalone
    ports:
    - '8080:8080'
    - '9990:9990'

volumes:
    jboss_deployments:
       driver: local

